CREATE TABLE COM_CUSTOMER (
	COM_CUSTOMER_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,        
	CUSTOMER_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE SALES_SO (
	SALES_SO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	SO_NO VARCHAR(20) NOT NULL,
	ORDER_DATE DATETIME NOT NULL,
	COM_CUSTOMER_ID INT NOT NULL,
	ADDRESS VARCHAR(500) NULL,
	CONSTRAINT FK_SO_CUTOMER FOREIGN KEY (COM_CUSTOMER_ID) REFERENCES COM_CUSTOMER(COM_CUSTOMER_ID)
);

CREATE TABLE SALES_SO_LITEM (
	SALES_SO_LITEM_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	SALES_SO_ID INT NOT NULL,
	ITEM_NAME VARCHAR(100) NOT NULL,
	QUANTITY INT NOT NULL,
	PRICE FLOAT NOT NULL,
	CONSTRAINT FK_LITEM_SO FOREIGN KEY (SALES_SO_ID) REFERENCES SALES_SO(SALES_SO_ID)
);

INSERT INTO COM_CUSTOMER VALUES ('PT Maju Bersama Abadi');
INSERT INTO COM_CUSTOMER VALUES ('CV Sejahtera Abadi');
INSERT INTO COM_CUSTOMER VALUES ('PT Karya Utama');

select * from COM_CUSTOMER;

select * from SALES_SO;

select * from SALES_SO_LITEM;